fn_single_line = true
imports_layout = "Vertical"
imports_granularity = "Crate"
reorder_impl_items = true
struct_field_align_threshold = 32
enum_discrim_align_threshold = 32
force_multiline_blocks = true
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
