os:
  - linux
  - windows
  - osx
language: rust
rust:
  - nightly
node_js:
  - node
cache:
  timeout: 360
  cargo: true
  yarn: true
  directories:
  - ui/node_modules
before_install:
  - bash ./scripts/before-install.sh
script:
  - bash ./scripts/build.sh
before_cache:
  - bash ./scripts/before-cache.sh
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S+)?$/
matrix:
  fast_finish: true
  allow_failures:
  - os: windows
addons:
  artifacts:
    debug: true
    working_dir: artifacts
    paths:
    - $(ls ./* | tr "\n" ":")
    target_paths:
    - /${TRAVIS_OS_NAME}/${TRAVIS_BUILD_NUMBER}
