os:
  - linux
  - windows
  - osx
language: rust
rust:
  - nightly
node_js:
  - node
cache:
  timeout: 360
  cargo: true
  yarn: true
  directories:
  - ui/node_modules
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then cinst yarn; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx"     ]; then brew install yarn; fi
script:
  - ls -l ./scripts
  - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then bash ./scripts/build-windows.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux"   ]; then bash ./scripts/build-linux.sh;   fi
  - if [ "${TRAVIS_OS_NAME}" = "osx"     ]; then bash ./scripts/build-macos.sh;   fi
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S+)?$/
