os:
  - linux
  - windows
  - osx
language: rust
rust:
  - nightly
node_js:
  - node
cache:
  timeout: 360
  cargo: true
  yarn: true
  directories:
  - ui/node_modules
before_install:
  - bash ./scripts/before-install.sh
script:
  - bash ./scripts/build.sh
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S+)?$/
