status = [
  "Rust app (macOS-latest)",
  "Rust app (ubuntu-latest)",
  "Rust app (windows-latest)"
]
block_labels = [
  "wip"
]
required_approvals = 0
use_codeowners = false
delete_merged_branches = true
