// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BigKey { easternPalace: boolean, desertPalace: boolean, towerOfHera: boolean, palaceOfDarkness: boolean, swampPalace: boolean, skullWoods: boolean, thievesTown: boolean, icePalace: boolean, miseryMire: boolean, turtleRock: boolean, gannonsTower: boolean, }