// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Bottle = "NoBottle" | "Mushroom" | "Empty" | "RedPotion" | "GreenPotion" | "BluePotion" | "Fairy" | "Bee" | "MagicBee";