// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Crystal { one: boolean, two: boolean, three: boolean, four: boolean, five: boolean, six: boolean, seven: boolean, }