// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DungeonAvailability = "desertPalace" | "easternPalace" | "ganonsTower" | "icePalace" | "miseryMire" | "palaceOfDarkness" | "skullWoods" | "swampPalace" | "thievesTown" | "towerOfHera" | "turtleRock";