// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DungeonReward } from "./DungeonReward";
import type { Medallion } from "./Medallion";

export interface DungeonUpdate { foundChests: number | null, reward: DungeonReward | null, medallion: Medallion | null, cleared: boolean | null, }