// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Availability } from "./Availability";
import type { LocationPosition } from "./LocationPosition";

export interface Location { name: string, hoverText: string, position: LocationPosition, cleared: boolean, availability: Availability, }