// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationCoordinates } from "./LocationCoordinates";

export interface LocationPosition { horizontal: LocationCoordinates, vertical: LocationCoordinates, }