// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataSourceType } from "./DataSourceType";
import type { RandoLogic } from "./RandoLogic";

export interface ServerConfigUpdate { dataPollRate: number | null, dataSource: string | null, logic: RandoLogic | null, sourceType: DataSourceType | null, }