// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataSourceType } from "./DataSourceType";
import type { RandoLogic } from "./RandoLogic";

export interface ServerConfig { apiPort: number, dataPollRate: number, dataSource: string, logic: RandoLogic, qusbDevices: Array<string>, sourceType: DataSourceType, }