name: Build and test
on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master
jobs:
  web-ui:
    name: Vue.js app

    strategy:
      matrix:
        node-version:
        - 12.x

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        cd ui
        yarn install
    - name: Test
      run: |
        cd ui
        yarn run unit
        yarn run build
    - name: Build
      run: |
        cd ui
        yarn run build
    - uses: actions/upload-artifact@master
      with:
        name: ui-dist
        path: ui/dist

  rust-app:
    name: Rust app
    needs:
    - web-ui

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@master
      with:
        name: ui-dist
        path: ui/dist
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose
      env:
        SKIP_UI_BUILD: true
    - name: Test
      uses: actions-rs/cargo@v1
      env:
        SKIP_UI_BUILD: true
      with:
        command: test
        args: --verbose
    - name: Upload debug artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@master
      with:
        name: debug_${{ matrix.os }}
        path: target/debug/sd2snes-lttp-rando-tracker.exe
    - name: Upload debug artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@master
      with:
        name: debug_${{ matrix.os }}
        path: target/debug/sd2snes-lttp-rando-tracker
    - name: Build Release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release
      env:
        SKIP_UI_BUILD: true
    - name: Upload release artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@master
      with:
        name: release_${{ matrix.os }}
        path: target/release/sd2snes-lttp-rando-tracker.exe
    - name: Upload release artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@master
      with:
        name: release_${{ matrix.os }}
        path: target/release/sd2snes-lttp-rando-tracker
