name: Release
on:
  push:
    tags:
      - v*
jobs:
  create-release:
    name: Create draft release
    needs:
      - rust-app
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux binary
        uses: actions/download-artifact@v3.0.2
        with:
          name: app_ubuntu-latest
          path: app/ubuntu
      - name: Create Linux Release Artifact
        run: |
          tar -czvf sd2snes-lttp-rando-tracker-linux-release.tar.gz -C app/ubuntu .
      - name: Download Windows binary
        uses: actions/download-artifact@v3.0.2
        with:
          name: app_windows-latest
          path: app/windows
      - name: Create Windows Release Artifact
        run: |
          zip --junk-paths sd2snes-lttp-rando-tracker-windows-release.zip app/windows/sd2snes-*
      - name: Download macOS binary
        uses: actions/download-artifact@v3.0.2
        with:
          name: app_macOS-latest
          path: app/macos
      - name: Create macOS Release Artifact
        run: |
          tar -czvf sd2snes-lttp-rando-tracker-macos-release.tar.gz -C app/macos .
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: |
            sd2snes-*-release.*

  web-ui:
    name: Vue.js app
    strategy:
      matrix:
        node-version:
          - 18.13.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ui/package-lock.json
      - name: Install
        run: |
          cd ui
          npm install
      - name: Build
        run: |
          cd ui
          npm run build
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ui-dist
          path: ui/dist

  rust-app:
    name: Rust app
    needs:
      - web-ui
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/download-artifact@v3.0.2
        with:
          name: ui-dist
          path: ui/dist
      - name: Install Rust
        run:
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - uses: actions/cache@v3.2.3
        name: Cache cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run:
          cargo test --verbose
      - name: Build
        run:
          cargo build --verbose --release
      - name: Upload release artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app_${{ matrix.os }}
          path: |
            target/release/sd2snes-lttp-rando-tracker*
            !**/*.d
            !**/*.pdb
